import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

const ImageContainer = (props) => {
  return <div style={{ position: 'fixed', bottom: 0, height: props.height, overflow: 'hidden' }}>{props.children}</div>
}

const Home: NextPage = () => {
  const [ scrollY, setScrollY ] = useState(0)
  const [ windowHeight, setWindowHeight ] = useState(0)
  const [ windowWidth, setWindowWidth ] = useState(0)
  
  function handleScroll(): void {
      setScrollY(window.scrollY)
    }

  function handleResize(): void {
      setWindowHeight(window.innerHeight);
      setWindowWidth(window.innerWidth)
    }

  useEffect(() => {
      window.addEventListener('scroll', handleScroll, {
          passive: true
        })

      window.addEventListener('resize', handleResize, {
          passive: true
        })
      
      handleResize()
    }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{height: windowHeight*3, display: 'flex', flexDirection: 'column', zIndex: 1}}>
        </div>
        <div style={{ position: 'fixed', bottom: 0, height: Math.max(0, windowHeight), overflow: 'hidden' }}>
          <Image src="/david-van-dijk-3LTht2nxd34-unsplash.jpg" layout="fixed" height={windowHeight} width={windowWidth} objectFit='cover' objectPosition="center top" alt="background"/>
        </div>
        <div style={{ position: 'fixed', bottom: 0, height: Math.max(0, scrollY), overflow: 'hidden' }}>
          <Image src="/sebastian-svenson-d2w-_1LJioQ-unsplash.jpg" layout="fixed" height={windowHeight} width={windowWidth} objectFit='cover' objectPosition="center top" alt="background"/>
        </div>
        <div style={{ position: 'fixed', bottom: 0, height: Math.max(0, scrollY-windowHeight), overflow: 'hidden' }}>
          <Image src="/david-van-dijk-3LTht2nxd34-unsplash.jpg" layout="fixed" height={windowHeight} width={windowWidth} objectFit='cover' objectPosition="center top" alt="background"/>
        </div>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
