import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { EmptyWallet, Verify, Edit, KeyboardOpen } from "iconsax-react";
import { useBudouX } from "../hooks/useBudouX";

const ImageContainer = (props) => {
  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        height: props.height,
        overflow: "hidden",
      }}
    >
      {props.children}
    </div>
  );
};

const MemoImage = React.memo((props) => {
  return (
    <Image
      src={props.imageUrl}
      layout="fixed"
      height={props.windowHeight}
      width={props.windowWidth}
      objectFit="cover"
      objectPosition="center top"
      alt="background"
    />
  )
})

const Home: NextPage = () => {
  const [scrollY, setScrollY] = useState(0);
  const [windowHeight, setWindowHeight] = useState(0);
  const [windowWidth, setWindowWidth] = useState(0);

  const { parse } = useBudouX();

  var throttle = (function (callback, interval = 256) {
    var time = Date.now(),
      lag,
      debounceTimer,
      debounceDelay = 16;

    return function (callback) {
      lag = time + interval - Date.now();
      if (lag < 0) {
        //console.log( time + "：throttle：" + lag);
        callback();
        time = Date.now();
      } else {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(function () {
          //console.log( time + "：debounce：" + (interval - lag + debounceDelay));
          callback();
        }, interval - lag + debounceDelay);
      }
    };
  })();

  // 間引きしたい処理
  var myCallback = function () {
    handleScroll();
  };

  function handleScroll(): void {
    setScrollY(window.scrollY);
  }

  function handleResize(): void {
    setWindowHeight(window.innerHeight);
    setWindowWidth(window.innerWidth);
  }

  useEffect(() => {
    window.addEventListener("scroll", handleScroll, {
      passive: true,
    });

    window.addEventListener("resize", handleResize, {
      passive: true,
    });

    handleResize();
  }, []);

  return (
    <div className={styles.container} style={{ backgroundColor: "black" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;1,100&family=Shippori+Mincho:wght@400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        <div
          style={{
            height: windowHeight * 5 + 250,
            width: "100%",
            display: "flex",
            flexDirection: "column",
            zIndex: 1,
            backgroundColor: "rgba(0, 0, 0, 0.5)",
          }}
        >
          {/* window 1 */}
          <div
            style={{
              height: windowHeight,
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              opacity: Math.min(
                Math.max(
                  1 - scrollY * 2 / windowHeight,
                  0
                ),
              1)
            }}
          >
            <text
              style={{
                fontSize: 40,
                fontWeight: "bold",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              ホームページ作成、どこも高くない？
            </text>
          </div>
          {/* window 2 */}
          <div
            style={{
              height: windowHeight,
              width: windowWidth * 0.5,
              display: "flex",
              flexDirection: "column",
              justifyContent: "end",
              alignItems: "start",
              marginLeft:
                150 -
                Math.min(
                  Math.max(
                    (scrollY - windowHeight * 0.75) / (windowHeight * 0.25),
                    0
                  ),
                  1
                ) * 100,
              paddingBottom: 150,
              opacity: Math.min(
                Math.max(
                  (scrollY - windowHeight * 0.75) / (windowHeight * 0.5),
                  0
                ),
                1
              ),
            }}
          >
            <div style={{ marginBottom: 10 }}>
              <EmptyWallet size="24" color="white" />
              <text
                style={{
                  fontSize: 20,
                  fontWeight: "normal",
                  color: "white",
                  fontFamily: "Shippori Mincho, serif",
                  marginLeft: 10,
                }}
              >
                手軽に始められる
              </text>
            </div>
            <text
              style={{
                fontSize: 32,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
                marginBottom: 20,
              }}
            >
              {parse(
                "SUGOI株式会社なら、月々3,000円から、自分だけのホームページが作れます。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "お店を開いたり、ビジネスを始めた直後だと、なかなか心理的にも金銭的にも余裕がないと思います。そんななか、ホームページの制作に時間やお金をとられると大変でしょう。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "私達は、あなたの要望を形にするお手伝いをします。丸投げで構いません。ホームページ制作は、私達にまかせて、従業員を集めたり、製品開発に励んだりと、あなたにしかできないことに時間を使ってください。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "また、最初はお金がたくさんかかると思います。あなたのビジネスが軌道に乗ってきてから、費用はお支払いいただければけっこうです。月々3,000円から、サブスク型でホームページの作成を請け負います。"
              )}
            </text>
          </div>
          {/* window 3 */}
          <div
            style={{
              height: windowHeight,
              width: windowWidth * 0.5,
              display: "flex",
              flexDirection: "column",
              justifyContent: "end",
              alignItems: "start",
              alignSelf: "end",
              marginRight: 
                150 -
                Math.min(
                  Math.max(
                    (scrollY - windowHeight * 1.75) / (windowHeight * 0.25),
                    0
                  ),
                  1
                ) * 100,
              paddingBottom: 150,
              opacity: Math.min(
                Math.max(
                  (scrollY - windowHeight * 1.75) / (windowHeight * 0.5),
                  0
                ),
                1
              ),
            }}
          >
            <div style={{ marginBottom: 10 }}>
              <Verify size="24" color="white" />
              <text
                style={{
                  fontSize: 20,
                  fontWeight: "normal",
                  color: "white",
                  fontFamily: "Shippori Mincho, serif",
                  marginLeft: 10,
                }}
              >
                信頼が得られる
              </text>
            </div>
            <text
              style={{
                fontSize: 32,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
                marginBottom: 20,
              }}
            >
              {parse("高品質なホームページで、お客様から信頼を得られます。")}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "ホームページは、ときに会社の顔になり、第一印象を左右するものでもあります。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "専属のデザイナーとエンジニアが、あなたのホームページを１から作ります。また、あなたのお店や会社のイメージや、ビジョンについてもぜひお聞かせください。それを踏まえ、私達からホームページを提案させていただければ幸いです。"
              )}
            </text>
          </div>
          {/* window 4 */}
          <div
            style={{
              height: windowHeight,
              width: windowWidth * 0.5,
              display: "flex",
              flexDirection: "column",
              justifyContent: "end",
              alignItems: "start",
              alignSelf: "start",
              marginLeft: 
                150 -
                Math.min(
                  Math.max(
                    (scrollY - windowHeight * 2.75) / (windowHeight * 0.25),
                    0
                  ),
                  1
                ) * 100,
              paddingBottom: 150,
              opacity: Math.min(
                Math.max(
                  (scrollY - windowHeight * 2.75) / (windowHeight * 0.5),
                  0
                ),
                1
              ),
            }}
          >
            <div style={{ marginBottom: 10 }}>
              <Edit size="24" color="white" />
              <text
                style={{
                  fontSize: 20,
                  fontWeight: "normal",
                  color: "white",
                  fontFamily: "Shippori Mincho, serif",
                  marginLeft: 10,
                }}
              >
                自由に内容を編集できる
              </text>
            </div>
            <text
              style={{
                fontSize: 32,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
                marginBottom: 20,
              }}
            >
              {parse("あなた自身で、ホームページの内容を編集できます。")}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "ホームページの内容を、あなた自身で、簡単に編集することが可能です。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "ブログのように、コンテンツを追加していくことで、ますますあなたらしく、ホームページを彩ってください。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse("")}
            </text>
          </div>
          {/* window 5 */}
          <div
            style={{
              height: windowHeight,
              width: windowWidth * 0.5,
              display: "flex",
              flexDirection: "column",
              justifyContent: "end",
              alignItems: "start",
              alignSelf: "end",
              marginRight: 
                150 -
                Math.min(
                  Math.max(
                    (scrollY - windowHeight * 3.75) / (windowHeight * 0.25),
                    0
                  ),
                  1
                ) * 100,
              paddingBottom: 150,
              opacity: Math.min(
                Math.max(
                  (scrollY - windowHeight * 3.75) / (windowHeight * 0.5),
                  0
                ),
                1
              ),
            }}
          >
            <div style={{ marginBottom: 10 }}>
              <KeyboardOpen size="24" color="white" />
              <text
                style={{
                  fontSize: 20,
                  fontWeight: "normal",
                  color: "white",
                  fontFamily: "Shippori Mincho, serif",
                  marginLeft: 10,
                }}
              >
                ホームページに限りません
              </text>
            </div>
            <text
              style={{
                fontSize: 32,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
                marginBottom: 20,
              }}
            >
              {parse("モバイルアプリやECサイトなども、ご相談ください")}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "ホームページを作り、集客がうまくいき、専用のモバイルアプリやECサイトが作りたくなるかもしれません。そんなときも、私達に任せてください。"
              )}
            </text>
            <text
              style={{
                fontSize: 16,
                fontWeight: "normal",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              {parse(
                "モバイルアプリ開発やECサイト制作の経験のある、私達のデザイナーやエンジニアが、あなたのビジネスを加速させるお手伝いをいたします。"
              )}
            </text>
          </div>
          {/* footer */}
          <div
            style={{
              position: "relative",
              height: 250,
              width: "100%",
              bottom: 0,
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
              backgroundColor: "black",
            }}
          >
            <text
              style={{
                fontSize: 24,
                fontWeight: "bold",
                color: "white",
                fontFamily: "Shippori Mincho, serif",
              }}
            >
              SUGOI株式会社
            </text>
          </div>
        </div>
        <div
          style={{
            position: "fixed",
            top: 0,
            height: Math.max(0, windowHeight * 5 - scrollY),
            overflow: "hidden",
          }}
        >
          <MemoImage imageUrl="/philipp-katzenberger-iIJrUoeRoCQ-unsplash.jpg" windowHeight={windowHeight} windowWidth={windowWidth}/>
        </div>
        <div
          style={{
            position: "fixed",
            top: 0,
            height: Math.max(0, windowHeight * 4 - scrollY),
            overflow: "hidden",
          }}
        >
          <MemoImage imageUrl="/darryl-brian-bDn1Wi1ixLw-unsplash.jpg" windowHeight={windowHeight} windowWidth={windowWidth}/>
        </div>
        <div
          style={{
            position: "fixed",
            top: 0,
            height: Math.max(0, windowHeight * 3 - scrollY),
            overflow: "hidden",
          }}
        >
          <MemoImage imageUrl="/artur-aldyrkhanov-3bwMp-TyxOE-unsplash.jpg" windowHeight={windowHeight} windowWidth={windowWidth}/>
        </div>
        <div
          style={{
            position: "fixed",
            top: 0,
            height: Math.max(0, windowHeight * 2 - scrollY),
            overflow: "hidden",
          }}
        >
          <MemoImage imageUrl="/david-van-dijk-3LTht2nxd34-unsplash.jpg" windowHeight={windowHeight} windowWidth={windowWidth}/>
        </div>
        <div
          style={{
            position: "fixed",
            top: 0,
            height: Math.max(0, windowHeight - scrollY),
            overflow: "hidden",
          }}
        >
          <div style={{position: 'absolute', zIndex: 1, height: '100%', width: '100%'}}><text style={{ color: 'white', position: 'absolute', bottom: 150}}>test</text></div>
          <MemoImage imageUrl="/sebastian-svenson-LpbyDENbQQg-unsplash.jpg" windowHeight={windowHeight} windowWidth={windowWidth}/>
        </div>
      </main>
    </div>
  );
};

export default Home;
